server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:./build/database/user;AUTO_SERVER=TRUE
    username: user
    password: user

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/user