server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./build/database/user;AUTO_SERVER=TRUE
    username: user
    password: user

    jpa:
      hibernate:
        ddl-auto: validate
      cloud:
        refresh:
          # Needed to resolve bug using schema.sql with spring cloud
          enabled: false

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/user