apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  type: NodePort
  ports:
    - port: 8761
      nodePort: 30761
      protocol: TCP