apiVersion: v1
kind: Service
metadata:
  name: note-service
  labels:
    app: note-service
spec:
  selector:
    app: note-service
  type: NodePort
  ports:
    - port: 8030
      nodePort: 30030
      protocol: TCP