apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service-deployment
  labels:
    app: note-service
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
        - name: note-service
          image: gcr.io/captech-microservices-training/cloud-training-demo/note
          resources:
            requests:
              memory: 768M
            limits:
              cpu: 0.5
          ports:
            - containerPort: 8030
          env:
            - name: spring.profiles.active
              value: docker
            - name: feign.client.config.default.connectTimeout
              value: "30000"
            - name: feign.client.config.default.readTimeout
              value: "30000"
            - name: eureka.client.registry-fetch-interval-seconds
              value: "10"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8030
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8030
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: note-service-horizontal-scaler
  labels:
    app: note-service
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: note-service-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50